version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  ApplicationStop:
    - location: stop_tomcat.sh
  install:
    - location: install.sh
  ApplicationStart:
    - location: start_tomcat.sh
